language: emacs-lisp
before_install:
  # PPA for stable Emacs packages
  - sudo add-apt-repository -y ppa:cassou/emacs
  # PPA for Emacs nightly builds
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  # update and install Emacs for our environment
  - sudo apt-get update -qq
  - sudo apt-get install -qq -yy ${EMACS}-nox ${EMACS}-el
  # install Cask
  - curl -fsSkL --max-time 10 --retry 10 --retry-delay 10
        https://raw.github.com/cask/cask/master/go | python
  - export PATH="/home/travis/.cask/bin:$PATH"
  - cask
env:
  - EMACS=emacs24
  - EMACS=emacs-snapshot
script:
  - emacs --version
  - make test

