language: emacs-lisp
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install emacs;
    fi
  # for Linux:
  # PPA for stable Emacs packages
  # PPA for Emacs nightly builds
  # update and install Emacs for our environment
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository -y ppa:cassou/emacs;
      sudo add-apt-repository -y ppa:ubuntu-elisp/ppa;
      sudo apt-get update -qq;
      sudo apt-get install -qq -yy ${EMACS}-nox ${EMACS}-el;
    fi
  # install Cask
  - curl -fsSkL --max-time 10 --retry 10 --retry-delay 10
        https://raw.github.com/cask/cask/master/go | python
  - cask
env:
  global:
    - CASK=$HOME/.cask/bin/cask
    - PATH=$HOME/.cask/bin:$PATH
matrix:
  include:
    - os: osx
      language: generic
      env: EMACS=emacs
      sudo: false
    - os: linux
      env: EMACS=emacs24
      sudo: required
    - os: linux
      env: EMACS=emacs-snapshot
      sudo: required
script:
  - emacs --version
  - make test
notifications:
  email: false

