language: emacs-lisp
os:
  - linux
  - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install emacs;
    fi
  # for Linux:
  # PPA for stable Emacs packages
  # PPA for Emacs nightly builds
  # update and install Emacs for our environment
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository -y ppa:cassou/emacs;
      sudo add-apt-repository -y ppa:ubuntu-elisp/ppa;
      sudo apt-get update -qq;
      sudo apt-get install -qq -yy ${EMACS}-nox ${EMACS}-el;
    fi
  # install Cask
  - curl -fsSkL --max-time 10 --retry 10 --retry-delay 10
        https://raw.github.com/cask/cask/master/go | python
  - export PATH="/home/travis/.cask/bin:$PATH"
  - cask
env:
  - EMACS=emacs24
  - EMACS=emacs-snapshot
script:
  - emacs --version
  - make test

